--- #creation of VM
- name: create azure VM
  hosts: localhost
  connection: local
  vars:
          resource_group: demo
          vm_name: testvm
          location: centralindia
  tasks:
        - name: create a resource group
          azure_rm_resourcegroup:
                  name: "{{ resource_group }}"
                  location: "{{ location }}"
        - name: create virtual network
          azure_rm_virtualnetwork:
                  resource_group: "{{ resource_group }}"
                  name: "{{ vm_name }}"
                  address_prefix: "10.0.1.0/16"
        - name: add subnet
          azure_rm_subnet:
                  resource_group: "{{ resource_group }}"
                  name: "{{ vm_name }}"
                  address_prefix: "10.0.1.0/24"
                  virtual_network: "{{ vm_name }}"
        - name: Create public IP address
          azure_rm_publicipaddress:
                  resource_group: "{{ resource_group }}"
                  allocation_method: Static
                  name: "{{ vm_name }}"
        - name: Create Network Security Group that allows SSH
          azure_rm_securitygroup:
                  resource_group: "{{ resource_group }}"
                  name: "{{ vm_name }}"
                  rules:
                          - name: SSH
                            protocol: Tcp
                            destination_port_range: 22
                            access: Allow
                            priority: 1001
                            direction: Inbound
        - name: Create VM
          azure_rm_virtualmachine:
                  resource_group: "{{ resource_group }}"
                  name: "{{ vm_name }}"
                  vm_size: Standard_DS1_v2
                  admin_username: azureuser
                  admin_password: Kamal@123456
                  network_interfaces: "{{ vm_name }}"
                  image:
                          offer: UbuntuServer
                          publisher: Canonical
                          sku: 20.04-LTS
                          version: latest
